### ISSUE TITLE
Invalid token format

### ISSUE THREAD

**Issue by colaholiker** [potofcoffee/pfarrplaner#57]
beim speichern kommt es zu einem Fehler.
User: <gerne per pm>
Url nach speichern: https://www.pfarrplaner.de/services/2081

Browser: Chrome und Firefox

die Änderungen sind aber gespeichert

(1/1) InvalidArgumentExceptionInvalid token format
--
in Client.php line 503
at Client->setAccessToken()in Broadcast.php line 109
at Broadcast->authenticate()in Broadcast.php line 86
at Broadcast::get()in ServiceController.php line 221
at ServiceController->update()in Controller.php line 54
at Controller->callAction()in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch()in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 681
at Router->Illuminate\Routing\{closure}()in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}()in Middleware.php line 82
at Middleware->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in LogVisits.php line 39
at LogVisits->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in SubstituteBindings.php line 41
at SubstituteBindings->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in Authenticate.php line 43
at Authenticate->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in VerifyCsrfToken.php line 78
at VerifyCsrfToken->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in StartSession.php line 56
at StartSession->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in EncryptCookies.php line 67
at EncryptCookies->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 105
at Pipeline->then()in Router.php line 683
at Router->runRouteWithinStack()in Router.php line 658
at Router->runRoute()in Router.php line 624
at Router->dispatchToRoute()in Router.php line 613
at Router->dispatch()in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}()in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}()in TrustProxies.php line 57
at TrustProxies->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in TransformsRequest.php line 21
at TransformsRequest->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in TransformsRequest.php line 21
at TransformsRequest->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in ValidatePostSize.php line 27
at ValidatePostSize->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle()in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 105
at Pipeline->then()in Kernel.php line 145
at Kernel->sendRequestThroughRouter()in Kernel.php line 110
at Kernel->handle()in index.php line 83

**Comment by potofcoffee** [comment]
Pushed a hotfix to production.
